"""empty message

<<<<<<<< HEAD:migrations/versions/89460520b5d4_.py
Revision ID: 89460520b5d4
Revises: 
Create Date: 2023-12-13 18:36:17.193213
========
Revision ID: d1b61f362ee9
Revises: 
Create Date: 2023-12-13 21:49:08.084560
>>>>>>>> ec5adc027d784b87191badddbaa3c46e8207d005:migrations/versions/d1b61f362ee9_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/89460520b5d4_.py
revision = '89460520b5d4'
========
revision = 'd1b61f362ee9'
>>>>>>>> ec5adc027d784b87191badddbaa3c46e8207d005:migrations/versions/d1b61f362ee9_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('full_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
